//
//  TelexRules.swift
//  NAKL
//
//  Ported from telex-standard.h
//  Original copyright (C) 2002 by Dao Hai Lam, VISC Software & Security Consultant Company
//  Licensed under the GNU General Public License v2 or later.
//

import Foundation

struct VietCode {
    let c: UInt16
    let r1: UInt16
    let r2: UInt16
    init(_ c: UInt16, _ r1: UInt16, _ r2: UInt16 = 0) {
        self.c = c; self.r1 = r1; self.r2 = r2
    }
}

enum TelexRules {
    static let code_A: [VietCode] = [
        VietCode(Viet.A, Viet.A6),
        VietCode(Viet.A1, Viet.A61),
        VietCode(Viet.A2, Viet.A62),
        VietCode(Viet.A3, Viet.A63),
        VietCode(Viet.A4, Viet.A64),
        VietCode(Viet.A5, Viet.A65),
        VietCode(Viet.A6, Viet.A, Viet.A),
        VietCode(Viet.A61, Viet.A1, Viet.A),
        VietCode(Viet.A62, Viet.A2, Viet.A),
        VietCode(Viet.A63, Viet.A3, Viet.A),
        VietCode(Viet.A64, Viet.A4, Viet.A),
        VietCode(Viet.A65, Viet.A5, Viet.A),
        VietCode(Viet.A8, Viet.A6),
        VietCode(Viet.A81, Viet.A61),
        VietCode(Viet.A82, Viet.A62),
        VietCode(Viet.A83, Viet.A63),
        VietCode(Viet.A84, Viet.A64),
        VietCode(Viet.A85, Viet.A65),
        VietCode(Viet.a, Viet.a6),
        VietCode(Viet.a1, Viet.a61),
        VietCode(Viet.a2, Viet.a62),
        VietCode(Viet.a3, Viet.a63),
        VietCode(Viet.a4, Viet.a64),
        VietCode(Viet.a5, Viet.a65),
        VietCode(Viet.a6, Viet.a, Viet.A),
        VietCode(Viet.a61, Viet.a1, Viet.A),
        VietCode(Viet.a62, Viet.a2, Viet.A),
        VietCode(Viet.a63, Viet.a3, Viet.A),
        VietCode(Viet.a64, Viet.a4, Viet.A),
        VietCode(Viet.a65, Viet.a5, Viet.A),
        VietCode(Viet.a8, Viet.a6),
        VietCode(Viet.a81, Viet.a61),
        VietCode(Viet.a82, Viet.a62),
        VietCode(Viet.a83, Viet.a63),
        VietCode(Viet.a84, Viet.a64),
        VietCode(Viet.a85, Viet.a65)
    ]

    static let code_a: [VietCode] = [
        VietCode(Viet.A, Viet.A6),
        VietCode(Viet.A1, Viet.A61),
        VietCode(Viet.A2, Viet.A62),
        VietCode(Viet.A3, Viet.A63),
        VietCode(Viet.A4, Viet.A64),
        VietCode(Viet.A5, Viet.A65),
        VietCode(Viet.A6, Viet.A, Viet.a),
        VietCode(Viet.A61, Viet.A1, Viet.a),
        VietCode(Viet.A62, Viet.A2, Viet.a),
        VietCode(Viet.A63, Viet.A3, Viet.a),
        VietCode(Viet.A64, Viet.A4, Viet.a),
        VietCode(Viet.A65, Viet.A5, Viet.a),
        VietCode(Viet.A8, Viet.A6),
        VietCode(Viet.A81, Viet.A61),
        VietCode(Viet.A82, Viet.A62),
        VietCode(Viet.A83, Viet.A63),
        VietCode(Viet.A84, Viet.A64),
        VietCode(Viet.A85, Viet.A65),
        VietCode(Viet.a, Viet.a6),
        VietCode(Viet.a1, Viet.a61),
        VietCode(Viet.a2, Viet.a62),
        VietCode(Viet.a3, Viet.a63),
        VietCode(Viet.a4, Viet.a64),
        VietCode(Viet.a5, Viet.a65),
        VietCode(Viet.a6, Viet.a, Viet.a),
        VietCode(Viet.a61, Viet.a1, Viet.a),
        VietCode(Viet.a62, Viet.a2, Viet.a),
        VietCode(Viet.a63, Viet.a3, Viet.a),
        VietCode(Viet.a64, Viet.a4, Viet.a),
        VietCode(Viet.a65, Viet.a5, Viet.a),
        VietCode(Viet.a8, Viet.a6),
        VietCode(Viet.a81, Viet.a61),
        VietCode(Viet.a82, Viet.a62),
        VietCode(Viet.a83, Viet.a63),
        VietCode(Viet.a84, Viet.a64),
        VietCode(Viet.a85, Viet.a65)
    ]

    static let code_E: [VietCode] = [
        VietCode(Viet.E, Viet.E6),
        VietCode(Viet.E1, Viet.E61),
        VietCode(Viet.E2, Viet.E62),
        VietCode(Viet.E3, Viet.E63),
        VietCode(Viet.E4, Viet.E64),
        VietCode(Viet.E5, Viet.E65),
        VietCode(Viet.E6, Viet.E, Viet.E),
        VietCode(Viet.E61, Viet.E1, Viet.E),
        VietCode(Viet.E62, Viet.E2, Viet.E),
        VietCode(Viet.E63, Viet.E3, Viet.E),
        VietCode(Viet.E64, Viet.E4, Viet.E),
        VietCode(Viet.E65, Viet.E5, Viet.E),
        VietCode(Viet.e, Viet.e6),
        VietCode(Viet.e1, Viet.e61),
        VietCode(Viet.e2, Viet.e62),
        VietCode(Viet.e3, Viet.e63),
        VietCode(Viet.e4, Viet.e64),
        VietCode(Viet.e5, Viet.e65),
        VietCode(Viet.e6, Viet.e, Viet.E),
        VietCode(Viet.e61, Viet.e1, Viet.E),
        VietCode(Viet.e62, Viet.e2, Viet.E),
        VietCode(Viet.e63, Viet.e3, Viet.E),
        VietCode(Viet.e64, Viet.e4, Viet.E),
        VietCode(Viet.e65, Viet.e5, Viet.E)
    ]

    static let code_e: [VietCode] = [
        VietCode(Viet.E, Viet.E6),
        VietCode(Viet.E1, Viet.E61),
        VietCode(Viet.E2, Viet.E62),
        VietCode(Viet.E3, Viet.E63),
        VietCode(Viet.E4, Viet.E64),
        VietCode(Viet.E5, Viet.E65),
        VietCode(Viet.E6, Viet.E, Viet.e),
        VietCode(Viet.E61, Viet.E1, Viet.e),
        VietCode(Viet.E62, Viet.E2, Viet.e),
        VietCode(Viet.E63, Viet.E3, Viet.e),
        VietCode(Viet.E64, Viet.E4, Viet.e),
        VietCode(Viet.E65, Viet.E5, Viet.e),
        VietCode(Viet.e, Viet.e6),
        VietCode(Viet.e1, Viet.e61),
        VietCode(Viet.e2, Viet.e62),
        VietCode(Viet.e3, Viet.e63),
        VietCode(Viet.e4, Viet.e64),
        VietCode(Viet.e5, Viet.e65),
        VietCode(Viet.e6, Viet.e, Viet.e),
        VietCode(Viet.e61, Viet.e1, Viet.e),
        VietCode(Viet.e62, Viet.e2, Viet.e),
        VietCode(Viet.e63, Viet.e3, Viet.e),
        VietCode(Viet.e64, Viet.e4, Viet.e),
        VietCode(Viet.e65, Viet.e5, Viet.e)
    ]

    static let code_O: [VietCode] = [
        VietCode(Viet.O, Viet.O6),
        VietCode(Viet.O1, Viet.O61),
        VietCode(Viet.O2, Viet.O62),
        VietCode(Viet.O3, Viet.O63),
        VietCode(Viet.O4, Viet.O64),
        VietCode(Viet.O5, Viet.O65),
        VietCode(Viet.O6, Viet.O, Viet.O),
        VietCode(Viet.O61, Viet.O1, Viet.O),
        VietCode(Viet.O62, Viet.O2, Viet.O),
        VietCode(Viet.O63, Viet.O3, Viet.O),
        VietCode(Viet.O64, Viet.O4, Viet.O),
        VietCode(Viet.O65, Viet.O5, Viet.O),
        VietCode(Viet.O7, Viet.O6),
        VietCode(Viet.O71, Viet.O61),
        VietCode(Viet.O72, Viet.O62),
        VietCode(Viet.O73, Viet.O63),
        VietCode(Viet.O74, Viet.O64),
        VietCode(Viet.O75, Viet.O65),
        VietCode(Viet.o, Viet.o6),
        VietCode(Viet.o1, Viet.o61),
        VietCode(Viet.o2, Viet.o62),
        VietCode(Viet.o3, Viet.o63),
        VietCode(Viet.o4, Viet.o64),
        VietCode(Viet.o5, Viet.o65),
        VietCode(Viet.o6, Viet.o, Viet.O),
        VietCode(Viet.o61, Viet.o1, Viet.O),
        VietCode(Viet.o62, Viet.o2, Viet.O),
        VietCode(Viet.o63, Viet.o3, Viet.O),
        VietCode(Viet.o64, Viet.o4, Viet.O),
        VietCode(Viet.o65, Viet.o5, Viet.O),
        VietCode(Viet.o7, Viet.o6),
        VietCode(Viet.o71, Viet.o61),
        VietCode(Viet.o72, Viet.o62),
        VietCode(Viet.o73, Viet.o63),
        VietCode(Viet.o74, Viet.o64),
        VietCode(Viet.o75, Viet.o65)
    ]

    static let code_o: [VietCode] = [
        VietCode(Viet.O, Viet.O6),
        VietCode(Viet.O1, Viet.O61),
        VietCode(Viet.O2, Viet.O62),
        VietCode(Viet.O3, Viet.O63),
        VietCode(Viet.O4, Viet.O64),
        VietCode(Viet.O5, Viet.O65),
        VietCode(Viet.O6, Viet.O, Viet.o),
        VietCode(Viet.O61, Viet.O1, Viet.o),
        VietCode(Viet.O62, Viet.O2, Viet.o),
        VietCode(Viet.O63, Viet.O3, Viet.o),
        VietCode(Viet.O64, Viet.O4, Viet.o),
        VietCode(Viet.O65, Viet.O5, Viet.o),
        VietCode(Viet.O7, Viet.O6),
        VietCode(Viet.O71, Viet.O61),
        VietCode(Viet.O72, Viet.O62),
        VietCode(Viet.O73, Viet.O63),
        VietCode(Viet.O74, Viet.O64),
        VietCode(Viet.O75, Viet.O65),
        VietCode(Viet.o, Viet.o6),
        VietCode(Viet.o1, Viet.o61),
        VietCode(Viet.o2, Viet.o62),
        VietCode(Viet.o3, Viet.o63),
        VietCode(Viet.o4, Viet.o64),
        VietCode(Viet.o5, Viet.o65),
        VietCode(Viet.o6, Viet.o, Viet.o),
        VietCode(Viet.o61, Viet.o1, Viet.o),
        VietCode(Viet.o62, Viet.o2, Viet.o),
        VietCode(Viet.o63, Viet.o3, Viet.o),
        VietCode(Viet.o64, Viet.o4, Viet.o),
        VietCode(Viet.o65, Viet.o5, Viet.o),
        VietCode(Viet.o7, Viet.o6),
        VietCode(Viet.o71, Viet.o61),
        VietCode(Viet.o72, Viet.o62),
        VietCode(Viet.o73, Viet.o63),
        VietCode(Viet.o74, Viet.o64),
        VietCode(Viet.o75, Viet.o65)
    ]

    static let code_D: [VietCode] = [
        VietCode(Viet.D, Viet.D9),
        VietCode(Viet.D9, Viet.D, Viet.D),
        VietCode(Viet.d, Viet.d9),
        VietCode(Viet.d9, Viet.d, Viet.D)
    ]

    static let code_d: [VietCode] = [
        VietCode(Viet.D, Viet.D9),
        VietCode(Viet.D9, Viet.D, Viet.d),
        VietCode(Viet.d, Viet.d9),
        VietCode(Viet.d9, Viet.d, Viet.d)
    ]

    static let code_W: [VietCode] = [
        VietCode(Viet.A, Viet.A8),
        VietCode(Viet.A1, Viet.A81),
        VietCode(Viet.A2, Viet.A82),
        VietCode(Viet.A3, Viet.A83),
        VietCode(Viet.A4, Viet.A84),
        VietCode(Viet.A5, Viet.A85),
        VietCode(Viet.A6, Viet.A8),
        VietCode(Viet.A61, Viet.A81),
        VietCode(Viet.A62, Viet.A82),
        VietCode(Viet.A63, Viet.A83),
        VietCode(Viet.A64, Viet.A84),
        VietCode(Viet.A65, Viet.A85),
        VietCode(Viet.A8, Viet.A, Viet.W),
        VietCode(Viet.A81, Viet.A1, Viet.W),
        VietCode(Viet.A82, Viet.A2, Viet.W),
        VietCode(Viet.A83, Viet.A3, Viet.W),
        VietCode(Viet.A84, Viet.A4, Viet.W),
        VietCode(Viet.A85, Viet.A5, Viet.W),
        VietCode(Viet.a, Viet.a8),
        VietCode(Viet.a1, Viet.a81),
        VietCode(Viet.a2, Viet.a82),
        VietCode(Viet.a3, Viet.a83),
        VietCode(Viet.a4, Viet.a84),
        VietCode(Viet.a5, Viet.a85),
        VietCode(Viet.a6, Viet.a8),
        VietCode(Viet.a61, Viet.a81),
        VietCode(Viet.a62, Viet.a82),
        VietCode(Viet.a63, Viet.a83),
        VietCode(Viet.a64, Viet.a84),
        VietCode(Viet.a65, Viet.a85),
        VietCode(Viet.a8, Viet.a, Viet.W),
        VietCode(Viet.a81, Viet.a1, Viet.W),
        VietCode(Viet.a82, Viet.a2, Viet.W),
        VietCode(Viet.a83, Viet.a3, Viet.W),
        VietCode(Viet.a84, Viet.a4, Viet.W),
        VietCode(Viet.a85, Viet.a5, Viet.W),
        VietCode(Viet.O, Viet.O7),
        VietCode(Viet.O1, Viet.O71),
        VietCode(Viet.O2, Viet.O72),
        VietCode(Viet.O3, Viet.O73),
        VietCode(Viet.O4, Viet.O74),
        VietCode(Viet.O5, Viet.O75),
        VietCode(Viet.O6, Viet.O7),
        VietCode(Viet.O61, Viet.O71),
        VietCode(Viet.O62, Viet.O72),
        VietCode(Viet.O63, Viet.O73),
        VietCode(Viet.O64, Viet.O74),
        VietCode(Viet.O65, Viet.O75),
        VietCode(Viet.O7, Viet.O, Viet.W),
        VietCode(Viet.O71, Viet.O1, Viet.W),
        VietCode(Viet.O72, Viet.O2, Viet.W),
        VietCode(Viet.O73, Viet.O3, Viet.W),
        VietCode(Viet.O74, Viet.O4, Viet.W),
        VietCode(Viet.O75, Viet.O5, Viet.W),
        VietCode(Viet.o, Viet.o7),
        VietCode(Viet.o1, Viet.o71),
        VietCode(Viet.o2, Viet.o72),
        VietCode(Viet.o3, Viet.o73),
        VietCode(Viet.o4, Viet.o74),
        VietCode(Viet.o5, Viet.o75),
        VietCode(Viet.o6, Viet.o7),
        VietCode(Viet.o61, Viet.o71),
        VietCode(Viet.o62, Viet.o72),
        VietCode(Viet.o63, Viet.o73),
        VietCode(Viet.o64, Viet.o74),
        VietCode(Viet.o65, Viet.o75),
        VietCode(Viet.o7, Viet.o, Viet.W),
        VietCode(Viet.o71, Viet.o1, Viet.W),
        VietCode(Viet.o72, Viet.o2, Viet.W),
        VietCode(Viet.o73, Viet.o3, Viet.W),
        VietCode(Viet.o74, Viet.o4, Viet.W),
        VietCode(Viet.o75, Viet.o5, Viet.W),
        VietCode(Viet.U, Viet.U7),
        VietCode(Viet.U1, Viet.U71),
        VietCode(Viet.U2, Viet.U72),
        VietCode(Viet.U3, Viet.U73),
        VietCode(Viet.U4, Viet.U74),
        VietCode(Viet.U5, Viet.U75),
        VietCode(Viet.U7, Viet.U, Viet.W),
        VietCode(Viet.U71, Viet.U1, Viet.W),
        VietCode(Viet.U72, Viet.U2, Viet.W),
        VietCode(Viet.U73, Viet.U3, Viet.W),
        VietCode(Viet.U74, Viet.U4, Viet.W),
        VietCode(Viet.U75, Viet.U5, Viet.W),
        VietCode(Viet.u, Viet.u7),
        VietCode(Viet.u1, Viet.u71),
        VietCode(Viet.u2, Viet.u72),
        VietCode(Viet.u3, Viet.u73),
        VietCode(Viet.u4, Viet.u74),
        VietCode(Viet.u5, Viet.u75),
        VietCode(Viet.u7, Viet.u, Viet.W),
        VietCode(Viet.u71, Viet.u1, Viet.W),
        VietCode(Viet.u72, Viet.u2, Viet.W),
        VietCode(Viet.u73, Viet.u3, Viet.W),
        VietCode(Viet.u74, Viet.u4, Viet.W),
        VietCode(Viet.u75, Viet.u5, Viet.W)
    ]

    static let code_w: [VietCode] = [
        VietCode(Viet.A, Viet.A8),
        VietCode(Viet.A1, Viet.A81),
        VietCode(Viet.A2, Viet.A82),
        VietCode(Viet.A3, Viet.A83),
        VietCode(Viet.A4, Viet.A84),
        VietCode(Viet.A5, Viet.A85),
        VietCode(Viet.A6, Viet.A8),
        VietCode(Viet.A61, Viet.A81),
        VietCode(Viet.A62, Viet.A82),
        VietCode(Viet.A63, Viet.A83),
        VietCode(Viet.A64, Viet.A84),
        VietCode(Viet.A65, Viet.A85),
        VietCode(Viet.A8, Viet.A, Viet.w),
        VietCode(Viet.A81, Viet.A1, Viet.w),
        VietCode(Viet.A82, Viet.A2, Viet.w),
        VietCode(Viet.A83, Viet.A3, Viet.w),
        VietCode(Viet.A84, Viet.A4, Viet.w),
        VietCode(Viet.A85, Viet.A5, Viet.w),
        VietCode(Viet.a, Viet.a8),
        VietCode(Viet.a1, Viet.a81),
        VietCode(Viet.a2, Viet.a82),
        VietCode(Viet.a3, Viet.a83),
        VietCode(Viet.a4, Viet.a84),
        VietCode(Viet.a5, Viet.a85),
        VietCode(Viet.a6, Viet.a8),
        VietCode(Viet.a61, Viet.a81),
        VietCode(Viet.a62, Viet.a82),
        VietCode(Viet.a63, Viet.a83),
        VietCode(Viet.a64, Viet.a84),
        VietCode(Viet.a65, Viet.a85),
        VietCode(Viet.a8, Viet.a, Viet.w),
        VietCode(Viet.a81, Viet.a1, Viet.w),
        VietCode(Viet.a82, Viet.a2, Viet.w),
        VietCode(Viet.a83, Viet.a3, Viet.w),
        VietCode(Viet.a84, Viet.a4, Viet.w),
        VietCode(Viet.a85, Viet.a5, Viet.w),
        VietCode(Viet.O, Viet.O7),
        VietCode(Viet.O1, Viet.O71),
        VietCode(Viet.O2, Viet.O72),
        VietCode(Viet.O3, Viet.O73),
        VietCode(Viet.O4, Viet.O74),
        VietCode(Viet.O5, Viet.O75),
        VietCode(Viet.O6, Viet.O7),
        VietCode(Viet.O61, Viet.O71),
        VietCode(Viet.O62, Viet.O72),
        VietCode(Viet.O63, Viet.O73),
        VietCode(Viet.O64, Viet.O74),
        VietCode(Viet.O65, Viet.O75),
        VietCode(Viet.O7, Viet.O, Viet.w),
        VietCode(Viet.O71, Viet.O1, Viet.w),
        VietCode(Viet.O72, Viet.O2, Viet.w),
        VietCode(Viet.O73, Viet.O3, Viet.w),
        VietCode(Viet.O74, Viet.O4, Viet.w),
        VietCode(Viet.O75, Viet.O5, Viet.w),
        VietCode(Viet.o, Viet.o7),
        VietCode(Viet.o1, Viet.o71),
        VietCode(Viet.o2, Viet.o72),
        VietCode(Viet.o3, Viet.o73),
        VietCode(Viet.o4, Viet.o74),
        VietCode(Viet.o5, Viet.o75),
        VietCode(Viet.o6, Viet.o7),
        VietCode(Viet.o61, Viet.o71),
        VietCode(Viet.o62, Viet.o72),
        VietCode(Viet.o63, Viet.o73),
        VietCode(Viet.o64, Viet.o74),
        VietCode(Viet.o65, Viet.o75),
        VietCode(Viet.o7, Viet.o, Viet.w),
        VietCode(Viet.o71, Viet.o1, Viet.w),
        VietCode(Viet.o72, Viet.o2, Viet.w),
        VietCode(Viet.o73, Viet.o3, Viet.w),
        VietCode(Viet.o74, Viet.o4, Viet.w),
        VietCode(Viet.o75, Viet.o5, Viet.w),
        VietCode(Viet.U, Viet.U7),
        VietCode(Viet.U1, Viet.U71),
        VietCode(Viet.U2, Viet.U72),
        VietCode(Viet.U3, Viet.U73),
        VietCode(Viet.U4, Viet.U74),
        VietCode(Viet.U5, Viet.U75),
        VietCode(Viet.U7, Viet.U, Viet.w),
        VietCode(Viet.U71, Viet.U1, Viet.w),
        VietCode(Viet.U72, Viet.U2, Viet.w),
        VietCode(Viet.U73, Viet.U3, Viet.w),
        VietCode(Viet.U74, Viet.U4, Viet.w),
        VietCode(Viet.U75, Viet.U5, Viet.w),
        VietCode(Viet.u, Viet.u7),
        VietCode(Viet.u1, Viet.u71),
        VietCode(Viet.u2, Viet.u72),
        VietCode(Viet.u3, Viet.u73),
        VietCode(Viet.u4, Viet.u74),
        VietCode(Viet.u5, Viet.u75),
        VietCode(Viet.u7, Viet.u, Viet.w),
        VietCode(Viet.u71, Viet.u1, Viet.w),
        VietCode(Viet.u72, Viet.u2, Viet.w),
        VietCode(Viet.u73, Viet.u3, Viet.w),
        VietCode(Viet.u74, Viet.u4, Viet.w),
        VietCode(Viet.u75, Viet.u5, Viet.w)
    ]

    static let code_S: [VietCode] = [
        VietCode(Viet.A, Viet.A1),
        VietCode(Viet.A1, Viet.A, Viet.S),
        VietCode(Viet.A2, Viet.A1),
        VietCode(Viet.A3, Viet.A1),
        VietCode(Viet.A4, Viet.A1),
        VietCode(Viet.A5, Viet.A1),
        VietCode(Viet.a, Viet.a1),
        VietCode(Viet.a1, Viet.a, Viet.S),
        VietCode(Viet.a2, Viet.a1),
        VietCode(Viet.a3, Viet.a1),
        VietCode(Viet.a4, Viet.a1),
        VietCode(Viet.a5, Viet.a1),
        VietCode(Viet.A6, Viet.A61),
        VietCode(Viet.A61, Viet.A6, Viet.S),
        VietCode(Viet.A62, Viet.A61),
        VietCode(Viet.A63, Viet.A61),
        VietCode(Viet.A64, Viet.A61),
        VietCode(Viet.A65, Viet.A61),
        VietCode(Viet.a6, Viet.a61),
        VietCode(Viet.a61, Viet.a6, Viet.S),
        VietCode(Viet.a62, Viet.a61),
        VietCode(Viet.a63, Viet.a61),
        VietCode(Viet.a64, Viet.a61),
        VietCode(Viet.a65, Viet.a61),
        VietCode(Viet.A8, Viet.A81),
        VietCode(Viet.A81, Viet.A8, Viet.S),
        VietCode(Viet.A82, Viet.A81),
        VietCode(Viet.A83, Viet.A81),
        VietCode(Viet.A84, Viet.A81),
        VietCode(Viet.A85, Viet.A81),
        VietCode(Viet.a8, Viet.a81),
        VietCode(Viet.a81, Viet.a8, Viet.S),
        VietCode(Viet.a82, Viet.a81),
        VietCode(Viet.a83, Viet.a81),
        VietCode(Viet.a84, Viet.a81),
        VietCode(Viet.a85, Viet.a81),
        VietCode(Viet.E, Viet.E1),
        VietCode(Viet.E1, Viet.E, Viet.S),
        VietCode(Viet.E2, Viet.E1),
        VietCode(Viet.E3, Viet.E1),
        VietCode(Viet.E4, Viet.E1),
        VietCode(Viet.E5, Viet.E1),
        VietCode(Viet.e, Viet.e1),
        VietCode(Viet.e1, Viet.e, Viet.S),
        VietCode(Viet.e2, Viet.e1),
        VietCode(Viet.e3, Viet.e1),
        VietCode(Viet.e4, Viet.e1),
        VietCode(Viet.e5, Viet.e1),
        VietCode(Viet.E6, Viet.E61),
        VietCode(Viet.E61, Viet.E6, Viet.S),
        VietCode(Viet.E62, Viet.E61),
        VietCode(Viet.E63, Viet.E61),
        VietCode(Viet.E64, Viet.E61),
        VietCode(Viet.E65, Viet.E61),
        VietCode(Viet.e6, Viet.e61),
        VietCode(Viet.e61, Viet.e6, Viet.S),
        VietCode(Viet.e62, Viet.e61),
        VietCode(Viet.e63, Viet.e61),
        VietCode(Viet.e64, Viet.e61),
        VietCode(Viet.e65, Viet.e61),
        VietCode(Viet.O, Viet.O1),
        VietCode(Viet.O1, Viet.O, Viet.S),
        VietCode(Viet.O2, Viet.O1),
        VietCode(Viet.O3, Viet.O1),
        VietCode(Viet.O4, Viet.O1),
        VietCode(Viet.O5, Viet.O1),
        VietCode(Viet.o, Viet.o1),
        VietCode(Viet.o1, Viet.o, Viet.S),
        VietCode(Viet.o2, Viet.o1),
        VietCode(Viet.o3, Viet.o1),
        VietCode(Viet.o4, Viet.o1),
        VietCode(Viet.o5, Viet.o1),
        VietCode(Viet.O6, Viet.O61),
        VietCode(Viet.O61, Viet.O6, Viet.S),
        VietCode(Viet.O62, Viet.O61),
        VietCode(Viet.O63, Viet.O61),
        VietCode(Viet.O64, Viet.O61),
        VietCode(Viet.O65, Viet.O61),
        VietCode(Viet.o6, Viet.o61),
        VietCode(Viet.o61, Viet.o6, Viet.S),
        VietCode(Viet.o62, Viet.o61),
        VietCode(Viet.o63, Viet.o61),
        VietCode(Viet.o64, Viet.o61),
        VietCode(Viet.o65, Viet.o61),
        VietCode(Viet.O7, Viet.O71),
        VietCode(Viet.O71, Viet.O7, Viet.S),
        VietCode(Viet.O72, Viet.O71),
        VietCode(Viet.O73, Viet.O71),
        VietCode(Viet.O74, Viet.O71),
        VietCode(Viet.O75, Viet.O71),
        VietCode(Viet.o7, Viet.o71),
        VietCode(Viet.o71, Viet.o7, Viet.S),
        VietCode(Viet.o72, Viet.o71),
        VietCode(Viet.o73, Viet.o71),
        VietCode(Viet.o74, Viet.o71),
        VietCode(Viet.o75, Viet.o71),
        VietCode(Viet.U, Viet.U1),
        VietCode(Viet.U1, Viet.U, Viet.S),
        VietCode(Viet.U2, Viet.U1),
        VietCode(Viet.U3, Viet.U1),
        VietCode(Viet.U4, Viet.U1),
        VietCode(Viet.U5, Viet.U1),
        VietCode(Viet.u, Viet.u1),
        VietCode(Viet.u1, Viet.u, Viet.S),
        VietCode(Viet.u2, Viet.u1),
        VietCode(Viet.u3, Viet.u1),
        VietCode(Viet.u4, Viet.u1),
        VietCode(Viet.u5, Viet.u1),
        VietCode(Viet.U7, Viet.U71),
        VietCode(Viet.U71, Viet.U7, Viet.S),
        VietCode(Viet.U72, Viet.U71),
        VietCode(Viet.U73, Viet.U71),
        VietCode(Viet.U74, Viet.U71),
        VietCode(Viet.U75, Viet.U71),
        VietCode(Viet.u7, Viet.u71),
        VietCode(Viet.u71, Viet.u7, Viet.S),
        VietCode(Viet.u72, Viet.u71),
        VietCode(Viet.u73, Viet.u71),
        VietCode(Viet.u74, Viet.u71),
        VietCode(Viet.u75, Viet.u71),
        VietCode(Viet.I, Viet.I1),
        VietCode(Viet.I1, Viet.I, Viet.S),
        VietCode(Viet.I2, Viet.I1),
        VietCode(Viet.I3, Viet.I1),
        VietCode(Viet.I4, Viet.I1),
        VietCode(Viet.I5, Viet.I1),
        VietCode(Viet.i, Viet.i1),
        VietCode(Viet.i1, Viet.i, Viet.S),
        VietCode(Viet.i2, Viet.i1),
        VietCode(Viet.i3, Viet.i1),
        VietCode(Viet.i4, Viet.i1),
        VietCode(Viet.i5, Viet.i1),
        VietCode(Viet.Y, Viet.Y1),
        VietCode(Viet.Y1, Viet.Y, Viet.S),
        VietCode(Viet.Y2, Viet.Y1),
        VietCode(Viet.Y3, Viet.Y1),
        VietCode(Viet.Y4, Viet.Y1),
        VietCode(Viet.Y5, Viet.Y1),
        VietCode(Viet.y, Viet.y1),
        VietCode(Viet.y1, Viet.y, Viet.S),
        VietCode(Viet.y2, Viet.y1),
        VietCode(Viet.y3, Viet.y1),
        VietCode(Viet.y4, Viet.y1),
        VietCode(Viet.y5, Viet.y1)
    ]

    static let code_s: [VietCode] = [
        VietCode(Viet.A, Viet.A1),
        VietCode(Viet.A1, Viet.A, Viet.s),
        VietCode(Viet.A2, Viet.A1),
        VietCode(Viet.A3, Viet.A1),
        VietCode(Viet.A4, Viet.A1),
        VietCode(Viet.A5, Viet.A1),
        VietCode(Viet.a, Viet.a1),
        VietCode(Viet.a1, Viet.a, Viet.s),
        VietCode(Viet.a2, Viet.a1),
        VietCode(Viet.a3, Viet.a1),
        VietCode(Viet.a4, Viet.a1),
        VietCode(Viet.a5, Viet.a1),
        VietCode(Viet.A6, Viet.A61),
        VietCode(Viet.A61, Viet.A6, Viet.s),
        VietCode(Viet.A62, Viet.A61),
        VietCode(Viet.A63, Viet.A61),
        VietCode(Viet.A64, Viet.A61),
        VietCode(Viet.A65, Viet.A61),
        VietCode(Viet.a6, Viet.a61),
        VietCode(Viet.a61, Viet.a6, Viet.s),
        VietCode(Viet.a62, Viet.a61),
        VietCode(Viet.a63, Viet.a61),
        VietCode(Viet.a64, Viet.a61),
        VietCode(Viet.a65, Viet.a61),
        VietCode(Viet.A8, Viet.A81),
        VietCode(Viet.A81, Viet.A8, Viet.s),
        VietCode(Viet.A82, Viet.A81),
        VietCode(Viet.A83, Viet.A81),
        VietCode(Viet.A84, Viet.A81),
        VietCode(Viet.A85, Viet.A81),
        VietCode(Viet.a8, Viet.a81),
        VietCode(Viet.a81, Viet.a8, Viet.s),
        VietCode(Viet.a82, Viet.a81),
        VietCode(Viet.a83, Viet.a81),
        VietCode(Viet.a84, Viet.a81),
        VietCode(Viet.a85, Viet.a81),
        VietCode(Viet.E, Viet.E1),
        VietCode(Viet.E1, Viet.E, Viet.s),
        VietCode(Viet.E2, Viet.E1),
        VietCode(Viet.E3, Viet.E1),
        VietCode(Viet.E4, Viet.E1),
        VietCode(Viet.E5, Viet.E1),
        VietCode(Viet.e, Viet.e1),
        VietCode(Viet.e1, Viet.e, Viet.s),
        VietCode(Viet.e2, Viet.e1),
        VietCode(Viet.e3, Viet.e1),
        VietCode(Viet.e4, Viet.e1),
        VietCode(Viet.e5, Viet.e1),
        VietCode(Viet.E6, Viet.E61),
        VietCode(Viet.E61, Viet.E6, Viet.s),
        VietCode(Viet.E62, Viet.E61),
        VietCode(Viet.E63, Viet.E61),
        VietCode(Viet.E64, Viet.E61),
        VietCode(Viet.E65, Viet.E61),
        VietCode(Viet.e6, Viet.e61),
        VietCode(Viet.e61, Viet.e6, Viet.s),
        VietCode(Viet.e62, Viet.e61),
        VietCode(Viet.e63, Viet.e61),
        VietCode(Viet.e64, Viet.e61),
        VietCode(Viet.e65, Viet.e61),
        VietCode(Viet.O, Viet.O1),
        VietCode(Viet.O1, Viet.O, Viet.s),
        VietCode(Viet.O2, Viet.O1),
        VietCode(Viet.O3, Viet.O1),
        VietCode(Viet.O4, Viet.O1),
        VietCode(Viet.O5, Viet.O1),
        VietCode(Viet.o, Viet.o1),
        VietCode(Viet.o1, Viet.o, Viet.s),
        VietCode(Viet.o2, Viet.o1),
        VietCode(Viet.o3, Viet.o1),
        VietCode(Viet.o4, Viet.o1),
        VietCode(Viet.o5, Viet.o1),
        VietCode(Viet.O6, Viet.O61),
        VietCode(Viet.O61, Viet.O6, Viet.s),
        VietCode(Viet.O62, Viet.O61),
        VietCode(Viet.O63, Viet.O61),
        VietCode(Viet.O64, Viet.O61),
        VietCode(Viet.O65, Viet.O61),
        VietCode(Viet.o6, Viet.o61),
        VietCode(Viet.o61, Viet.o6, Viet.s),
        VietCode(Viet.o62, Viet.o61),
        VietCode(Viet.o63, Viet.o61),
        VietCode(Viet.o64, Viet.o61),
        VietCode(Viet.o65, Viet.o61),
        VietCode(Viet.O7, Viet.O71),
        VietCode(Viet.O71, Viet.O7, Viet.s),
        VietCode(Viet.O72, Viet.O71),
        VietCode(Viet.O73, Viet.O71),
        VietCode(Viet.O74, Viet.O71),
        VietCode(Viet.O75, Viet.O71),
        VietCode(Viet.o7, Viet.o71),
        VietCode(Viet.o71, Viet.o7, Viet.s),
        VietCode(Viet.o72, Viet.o71),
        VietCode(Viet.o73, Viet.o71),
        VietCode(Viet.o74, Viet.o71),
        VietCode(Viet.o75, Viet.o71),
        VietCode(Viet.U, Viet.U1),
        VietCode(Viet.U1, Viet.U, Viet.s),
        VietCode(Viet.U2, Viet.U1),
        VietCode(Viet.U3, Viet.U1),
        VietCode(Viet.U4, Viet.U1),
        VietCode(Viet.U5, Viet.U1),
        VietCode(Viet.u, Viet.u1),
        VietCode(Viet.u1, Viet.u, Viet.s),
        VietCode(Viet.u2, Viet.u1),
        VietCode(Viet.u3, Viet.u1),
        VietCode(Viet.u4, Viet.u1),
        VietCode(Viet.u5, Viet.u1),
        VietCode(Viet.U7, Viet.U71),
        VietCode(Viet.U71, Viet.U7, Viet.s),
        VietCode(Viet.U72, Viet.U71),
        VietCode(Viet.U73, Viet.U71),
        VietCode(Viet.U74, Viet.U71),
        VietCode(Viet.U75, Viet.U71),
        VietCode(Viet.u7, Viet.u71),
        VietCode(Viet.u71, Viet.u7, Viet.s),
        VietCode(Viet.u72, Viet.u71),
        VietCode(Viet.u73, Viet.u71),
        VietCode(Viet.u74, Viet.u71),
        VietCode(Viet.u75, Viet.u71),
        VietCode(Viet.I, Viet.I1),
        VietCode(Viet.I1, Viet.I, Viet.s),
        VietCode(Viet.I2, Viet.I1),
        VietCode(Viet.I3, Viet.I1),
        VietCode(Viet.I4, Viet.I1),
        VietCode(Viet.I5, Viet.I1),
        VietCode(Viet.i, Viet.i1),
        VietCode(Viet.i1, Viet.i, Viet.s),
        VietCode(Viet.i2, Viet.i1),
        VietCode(Viet.i3, Viet.i1),
        VietCode(Viet.i4, Viet.i1),
        VietCode(Viet.i5, Viet.i1),
        VietCode(Viet.Y, Viet.Y1),
        VietCode(Viet.Y1, Viet.Y, Viet.s),
        VietCode(Viet.Y2, Viet.Y1),
        VietCode(Viet.Y3, Viet.Y1),
        VietCode(Viet.Y4, Viet.Y1),
        VietCode(Viet.Y5, Viet.Y1),
        VietCode(Viet.y, Viet.y1),
        VietCode(Viet.y1, Viet.y, Viet.s),
        VietCode(Viet.y2, Viet.y1),
        VietCode(Viet.y3, Viet.y1),
        VietCode(Viet.y4, Viet.y1),
        VietCode(Viet.y5, Viet.y1)
    ]

    static let code_F: [VietCode] = [
        VietCode(Viet.A, Viet.A2),
        VietCode(Viet.A1, Viet.A2),
        VietCode(Viet.A2, Viet.A, Viet.F),
        VietCode(Viet.A3, Viet.A2),
        VietCode(Viet.A4, Viet.A2),
        VietCode(Viet.A5, Viet.A2),
        VietCode(Viet.a, Viet.a2),
        VietCode(Viet.a1, Viet.a2),
        VietCode(Viet.a2, Viet.a, Viet.F),
        VietCode(Viet.a3, Viet.a2),
        VietCode(Viet.a4, Viet.a2),
        VietCode(Viet.a5, Viet.a2),
        VietCode(Viet.A6, Viet.A62),
        VietCode(Viet.A61, Viet.A62),
        VietCode(Viet.A62, Viet.A6, Viet.F),
        VietCode(Viet.A63, Viet.A62),
        VietCode(Viet.A64, Viet.A62),
        VietCode(Viet.A65, Viet.A62),
        VietCode(Viet.a6, Viet.a62),
        VietCode(Viet.a61, Viet.a62),
        VietCode(Viet.a62, Viet.a6, Viet.F),
        VietCode(Viet.a63, Viet.a62),
        VietCode(Viet.a64, Viet.a62),
        VietCode(Viet.a65, Viet.a62),
        VietCode(Viet.A8, Viet.A82),
        VietCode(Viet.A81, Viet.A82),
        VietCode(Viet.A82, Viet.A8, Viet.F),
        VietCode(Viet.A83, Viet.A82),
        VietCode(Viet.A84, Viet.A82),
        VietCode(Viet.A85, Viet.A82),
        VietCode(Viet.a8, Viet.a82),
        VietCode(Viet.a81, Viet.a82),
        VietCode(Viet.a82, Viet.a8, Viet.F),
        VietCode(Viet.a83, Viet.a82),
        VietCode(Viet.a84, Viet.a82),
        VietCode(Viet.a85, Viet.a82),
        VietCode(Viet.E, Viet.E2),
        VietCode(Viet.E1, Viet.E2),
        VietCode(Viet.E2, Viet.E, Viet.F),
        VietCode(Viet.E3, Viet.E2),
        VietCode(Viet.E4, Viet.E2),
        VietCode(Viet.E5, Viet.E2),
        VietCode(Viet.e, Viet.e2),
        VietCode(Viet.e1, Viet.e2),
        VietCode(Viet.e2, Viet.e, Viet.F),
        VietCode(Viet.e3, Viet.e2),
        VietCode(Viet.e4, Viet.e2),
        VietCode(Viet.e5, Viet.e2),
        VietCode(Viet.E6, Viet.E62),
        VietCode(Viet.E61, Viet.E62),
        VietCode(Viet.E62, Viet.E6, Viet.F),
        VietCode(Viet.E63, Viet.E62),
        VietCode(Viet.E64, Viet.E62),
        VietCode(Viet.E65, Viet.E62),
        VietCode(Viet.e6, Viet.e62),
        VietCode(Viet.e61, Viet.e62),
        VietCode(Viet.e62, Viet.e6, Viet.F),
        VietCode(Viet.e63, Viet.e62),
        VietCode(Viet.e64, Viet.e62),
        VietCode(Viet.e65, Viet.e62),
        VietCode(Viet.O, Viet.O2),
        VietCode(Viet.O1, Viet.O2),
        VietCode(Viet.O2, Viet.O, Viet.F),
        VietCode(Viet.O3, Viet.O2),
        VietCode(Viet.O4, Viet.O2),
        VietCode(Viet.O5, Viet.O2),
        VietCode(Viet.o, Viet.o2),
        VietCode(Viet.o1, Viet.o2),
        VietCode(Viet.o2, Viet.o, Viet.F),
        VietCode(Viet.o3, Viet.o2),
        VietCode(Viet.o4, Viet.o2),
        VietCode(Viet.o5, Viet.o2),
        VietCode(Viet.O6, Viet.O62),
        VietCode(Viet.O61, Viet.O62),
        VietCode(Viet.O62, Viet.O6, Viet.F),
        VietCode(Viet.O63, Viet.O62),
        VietCode(Viet.O64, Viet.O62),
        VietCode(Viet.O65, Viet.O62),
        VietCode(Viet.o6, Viet.o62),
        VietCode(Viet.o61, Viet.o62),
        VietCode(Viet.o62, Viet.o6, Viet.F),
        VietCode(Viet.o63, Viet.o62),
        VietCode(Viet.o64, Viet.o62),
        VietCode(Viet.o65, Viet.o62),
        VietCode(Viet.O7, Viet.O72),
        VietCode(Viet.O71, Viet.O72),
        VietCode(Viet.O72, Viet.O7, Viet.F),
        VietCode(Viet.O73, Viet.O72),
        VietCode(Viet.O74, Viet.O72),
        VietCode(Viet.O75, Viet.O72),
        VietCode(Viet.o7, Viet.o72),
        VietCode(Viet.o71, Viet.o72),
        VietCode(Viet.o72, Viet.o7, Viet.F),
        VietCode(Viet.o73, Viet.o72),
        VietCode(Viet.o74, Viet.o72),
        VietCode(Viet.o75, Viet.o72),
        VietCode(Viet.U, Viet.U2),
        VietCode(Viet.U1, Viet.U2),
        VietCode(Viet.U2, Viet.U, Viet.F),
        VietCode(Viet.U3, Viet.U2),
        VietCode(Viet.U4, Viet.U2),
        VietCode(Viet.U5, Viet.U2),
        VietCode(Viet.u, Viet.u2),
        VietCode(Viet.u1, Viet.u2),
        VietCode(Viet.u2, Viet.u, Viet.F),
        VietCode(Viet.u3, Viet.u2),
        VietCode(Viet.u4, Viet.u2),
        VietCode(Viet.u5, Viet.u2),
        VietCode(Viet.U7, Viet.U72),
        VietCode(Viet.U71, Viet.U72),
        VietCode(Viet.U72, Viet.U7, Viet.F),
        VietCode(Viet.U73, Viet.U72),
        VietCode(Viet.U74, Viet.U72),
        VietCode(Viet.U75, Viet.U72),
        VietCode(Viet.u7, Viet.u72),
        VietCode(Viet.u71, Viet.u72),
        VietCode(Viet.u72, Viet.u7, Viet.F),
        VietCode(Viet.u73, Viet.u72),
        VietCode(Viet.u74, Viet.u72),
        VietCode(Viet.u75, Viet.u72),
        VietCode(Viet.I, Viet.I2),
        VietCode(Viet.I1, Viet.I2),
        VietCode(Viet.I2, Viet.I, Viet.F),
        VietCode(Viet.I3, Viet.I2),
        VietCode(Viet.I4, Viet.I2),
        VietCode(Viet.I5, Viet.I2),
        VietCode(Viet.i, Viet.i2),
        VietCode(Viet.i1, Viet.i2),
        VietCode(Viet.i2, Viet.i, Viet.F),
        VietCode(Viet.i3, Viet.i2),
        VietCode(Viet.i4, Viet.i2),
        VietCode(Viet.i5, Viet.i2),
        VietCode(Viet.Y, Viet.Y2),
        VietCode(Viet.Y1, Viet.Y2),
        VietCode(Viet.Y2, Viet.Y, Viet.F),
        VietCode(Viet.Y3, Viet.Y2),
        VietCode(Viet.Y4, Viet.Y2),
        VietCode(Viet.Y5, Viet.Y2),
        VietCode(Viet.y, Viet.y2),
        VietCode(Viet.y1, Viet.y2),
        VietCode(Viet.y2, Viet.y, Viet.F),
        VietCode(Viet.y3, Viet.y2),
        VietCode(Viet.y4, Viet.y2),
        VietCode(Viet.y5, Viet.y2)
    ]

    static let code_f: [VietCode] = [
        VietCode(Viet.A, Viet.A2),
        VietCode(Viet.A1, Viet.A2),
        VietCode(Viet.A2, Viet.A, Viet.f),
        VietCode(Viet.A3, Viet.A2),
        VietCode(Viet.A4, Viet.A2),
        VietCode(Viet.A5, Viet.A2),
        VietCode(Viet.a, Viet.a2),
        VietCode(Viet.a1, Viet.a2),
        VietCode(Viet.a2, Viet.a, Viet.f),
        VietCode(Viet.a3, Viet.a2),
        VietCode(Viet.a4, Viet.a2),
        VietCode(Viet.a5, Viet.a2),
        VietCode(Viet.A6, Viet.A62),
        VietCode(Viet.A61, Viet.A62),
        VietCode(Viet.A62, Viet.A6, Viet.f),
        VietCode(Viet.A63, Viet.A62),
        VietCode(Viet.A64, Viet.A62),
        VietCode(Viet.A65, Viet.A62),
        VietCode(Viet.a6, Viet.a62),
        VietCode(Viet.a61, Viet.a62),
        VietCode(Viet.a62, Viet.a6, Viet.f),
        VietCode(Viet.a63, Viet.a62),
        VietCode(Viet.a64, Viet.a62),
        VietCode(Viet.a65, Viet.a62),
        VietCode(Viet.A8, Viet.A82),
        VietCode(Viet.A81, Viet.A82),
        VietCode(Viet.A82, Viet.A8, Viet.f),
        VietCode(Viet.A83, Viet.A82),
        VietCode(Viet.A84, Viet.A82),
        VietCode(Viet.A85, Viet.A82),
        VietCode(Viet.a8, Viet.a82),
        VietCode(Viet.a81, Viet.a82),
        VietCode(Viet.a82, Viet.a8, Viet.f),
        VietCode(Viet.a83, Viet.a82),
        VietCode(Viet.a84, Viet.a82),
        VietCode(Viet.a85, Viet.a82),
        VietCode(Viet.E, Viet.E2),
        VietCode(Viet.E1, Viet.E2),
        VietCode(Viet.E2, Viet.E, Viet.f),
        VietCode(Viet.E3, Viet.E2),
        VietCode(Viet.E4, Viet.E2),
        VietCode(Viet.E5, Viet.E2),
        VietCode(Viet.e, Viet.e2),
        VietCode(Viet.e1, Viet.e2),
        VietCode(Viet.e2, Viet.e, Viet.f),
        VietCode(Viet.e3, Viet.e2),
        VietCode(Viet.e4, Viet.e2),
        VietCode(Viet.e5, Viet.e2),
        VietCode(Viet.E6, Viet.E62),
        VietCode(Viet.E61, Viet.E62),
        VietCode(Viet.E62, Viet.E6, Viet.f),
        VietCode(Viet.E63, Viet.E62),
        VietCode(Viet.E64, Viet.E62),
        VietCode(Viet.E65, Viet.E62),
        VietCode(Viet.e6, Viet.e62),
        VietCode(Viet.e61, Viet.e62),
        VietCode(Viet.e62, Viet.e6, Viet.f),
        VietCode(Viet.e63, Viet.e62),
        VietCode(Viet.e64, Viet.e62),
        VietCode(Viet.e65, Viet.e62),
        VietCode(Viet.O, Viet.O2),
        VietCode(Viet.O1, Viet.O2),
        VietCode(Viet.O2, Viet.O, Viet.f),
        VietCode(Viet.O3, Viet.O2),
        VietCode(Viet.O4, Viet.O2),
        VietCode(Viet.O5, Viet.O2),
        VietCode(Viet.o, Viet.o2),
        VietCode(Viet.o1, Viet.o2),
        VietCode(Viet.o2, Viet.o, Viet.f),
        VietCode(Viet.o3, Viet.o2),
        VietCode(Viet.o4, Viet.o2),
        VietCode(Viet.o5, Viet.o2),
        VietCode(Viet.O6, Viet.O62),
        VietCode(Viet.O61, Viet.O62),
        VietCode(Viet.O62, Viet.O6, Viet.f),
        VietCode(Viet.O63, Viet.O62),
        VietCode(Viet.O64, Viet.O62),
        VietCode(Viet.O65, Viet.O62),
        VietCode(Viet.o6, Viet.o62),
        VietCode(Viet.o61, Viet.o62),
        VietCode(Viet.o62, Viet.o6, Viet.f),
        VietCode(Viet.o63, Viet.o62),
        VietCode(Viet.o64, Viet.o62),
        VietCode(Viet.o65, Viet.o62),
        VietCode(Viet.O7, Viet.O72),
        VietCode(Viet.O71, Viet.O72),
        VietCode(Viet.O72, Viet.O7, Viet.f),
        VietCode(Viet.O73, Viet.O72),
        VietCode(Viet.O74, Viet.O72),
        VietCode(Viet.O75, Viet.O72),
        VietCode(Viet.o7, Viet.o72),
        VietCode(Viet.o71, Viet.o72),
        VietCode(Viet.o72, Viet.o7, Viet.f),
        VietCode(Viet.o73, Viet.o72),
        VietCode(Viet.o74, Viet.o72),
        VietCode(Viet.o75, Viet.o72),
        VietCode(Viet.U, Viet.U2),
        VietCode(Viet.U1, Viet.U2),
        VietCode(Viet.U2, Viet.U, Viet.f),
        VietCode(Viet.U3, Viet.U2),
        VietCode(Viet.U4, Viet.U2),
        VietCode(Viet.U5, Viet.U2),
        VietCode(Viet.u, Viet.u2),
        VietCode(Viet.u1, Viet.u2),
        VietCode(Viet.u2, Viet.u, Viet.f),
        VietCode(Viet.u3, Viet.u2),
        VietCode(Viet.u4, Viet.u2),
        VietCode(Viet.u5, Viet.u2),
        VietCode(Viet.U7, Viet.U72),
        VietCode(Viet.U71, Viet.U72),
        VietCode(Viet.U72, Viet.U7, Viet.f),
        VietCode(Viet.U73, Viet.U72),
        VietCode(Viet.U74, Viet.U72),
        VietCode(Viet.U75, Viet.U72),
        VietCode(Viet.u7, Viet.u72),
        VietCode(Viet.u71, Viet.u72),
        VietCode(Viet.u72, Viet.u7, Viet.f),
        VietCode(Viet.u73, Viet.u72),
        VietCode(Viet.u74, Viet.u72),
        VietCode(Viet.u75, Viet.u72),
        VietCode(Viet.I, Viet.I2),
        VietCode(Viet.I1, Viet.I2),
        VietCode(Viet.I2, Viet.I, Viet.f),
        VietCode(Viet.I3, Viet.I2),
        VietCode(Viet.I4, Viet.I2),
        VietCode(Viet.I5, Viet.I2),
        VietCode(Viet.i, Viet.i2),
        VietCode(Viet.i1, Viet.i2),
        VietCode(Viet.i2, Viet.i, Viet.f),
        VietCode(Viet.i3, Viet.i2),
        VietCode(Viet.i4, Viet.i2),
        VietCode(Viet.i5, Viet.i2),
        VietCode(Viet.Y, Viet.Y2),
        VietCode(Viet.Y1, Viet.Y2),
        VietCode(Viet.Y2, Viet.Y, Viet.f),
        VietCode(Viet.Y3, Viet.Y2),
        VietCode(Viet.Y4, Viet.Y2),
        VietCode(Viet.Y5, Viet.Y2),
        VietCode(Viet.y, Viet.y2),
        VietCode(Viet.y1, Viet.y2),
        VietCode(Viet.y2, Viet.y, Viet.f),
        VietCode(Viet.y3, Viet.y2),
        VietCode(Viet.y4, Viet.y2),
        VietCode(Viet.y5, Viet.y2)
    ]

    static let code_R: [VietCode] = [
        VietCode(Viet.A, Viet.A3),
        VietCode(Viet.A1, Viet.A3),
        VietCode(Viet.A2, Viet.A3),
        VietCode(Viet.A3, Viet.A, Viet.R),
        VietCode(Viet.A4, Viet.A3),
        VietCode(Viet.A5, Viet.A3),
        VietCode(Viet.a, Viet.a3),
        VietCode(Viet.a1, Viet.a3),
        VietCode(Viet.a2, Viet.a3),
        VietCode(Viet.a3, Viet.a, Viet.R),
        VietCode(Viet.a4, Viet.a3),
        VietCode(Viet.a5, Viet.a3),
        VietCode(Viet.A6, Viet.A63),
        VietCode(Viet.A61, Viet.A63),
        VietCode(Viet.A62, Viet.A63),
        VietCode(Viet.A63, Viet.A6, Viet.R),
        VietCode(Viet.A64, Viet.A63),
        VietCode(Viet.A65, Viet.A63),
        VietCode(Viet.a6, Viet.a63),
        VietCode(Viet.a61, Viet.a63),
        VietCode(Viet.a62, Viet.a63),
        VietCode(Viet.a63, Viet.a6, Viet.R),
        VietCode(Viet.a64, Viet.a63),
        VietCode(Viet.a65, Viet.a63),
        VietCode(Viet.A8, Viet.A83),
        VietCode(Viet.A81, Viet.A83),
        VietCode(Viet.A82, Viet.A83),
        VietCode(Viet.A83, Viet.A8, Viet.R),
        VietCode(Viet.A84, Viet.A83),
        VietCode(Viet.A85, Viet.A83),
        VietCode(Viet.a8, Viet.a83),
        VietCode(Viet.a81, Viet.a83),
        VietCode(Viet.a82, Viet.a83),
        VietCode(Viet.a83, Viet.a8, Viet.R),
        VietCode(Viet.a84, Viet.a83),
        VietCode(Viet.a85, Viet.a83),
        VietCode(Viet.E, Viet.E3),
        VietCode(Viet.E1, Viet.E3),
        VietCode(Viet.E2, Viet.E3),
        VietCode(Viet.E3, Viet.E, Viet.R),
        VietCode(Viet.E4, Viet.E3),
        VietCode(Viet.E5, Viet.E3),
        VietCode(Viet.e, Viet.e3),
        VietCode(Viet.e1, Viet.e3),
        VietCode(Viet.e2, Viet.e3),
        VietCode(Viet.e3, Viet.e, Viet.R),
        VietCode(Viet.e4, Viet.e3),
        VietCode(Viet.e5, Viet.e3),
        VietCode(Viet.E6, Viet.E63),
        VietCode(Viet.E61, Viet.E63),
        VietCode(Viet.E62, Viet.E63),
        VietCode(Viet.E63, Viet.E6, Viet.R),
        VietCode(Viet.E64, Viet.E63),
        VietCode(Viet.E65, Viet.E63),
        VietCode(Viet.e6, Viet.e63),
        VietCode(Viet.e61, Viet.e63),
        VietCode(Viet.e62, Viet.e63),
        VietCode(Viet.e63, Viet.e6, Viet.R),
        VietCode(Viet.e64, Viet.e63),
        VietCode(Viet.e65, Viet.e63),
        VietCode(Viet.O, Viet.O3),
        VietCode(Viet.O1, Viet.O3),
        VietCode(Viet.O2, Viet.O3),
        VietCode(Viet.O3, Viet.O, Viet.R),
        VietCode(Viet.O4, Viet.O3),
        VietCode(Viet.O5, Viet.O3),
        VietCode(Viet.o, Viet.o3),
        VietCode(Viet.o1, Viet.o3),
        VietCode(Viet.o2, Viet.o3),
        VietCode(Viet.o3, Viet.o, Viet.R),
        VietCode(Viet.o4, Viet.o3),
        VietCode(Viet.o5, Viet.o3),
        VietCode(Viet.O6, Viet.O63),
        VietCode(Viet.O61, Viet.O63),
        VietCode(Viet.O62, Viet.O63),
        VietCode(Viet.O63, Viet.O6, Viet.R),
        VietCode(Viet.O64, Viet.O63),
        VietCode(Viet.O65, Viet.O63),
        VietCode(Viet.o6, Viet.o63),
        VietCode(Viet.o61, Viet.o63),
        VietCode(Viet.o62, Viet.o63),
        VietCode(Viet.o63, Viet.o6, Viet.R),
        VietCode(Viet.o64, Viet.o63),
        VietCode(Viet.o65, Viet.o63),
        VietCode(Viet.O7, Viet.O73),
        VietCode(Viet.O71, Viet.O73),
        VietCode(Viet.O72, Viet.O73),
        VietCode(Viet.O73, Viet.O7, Viet.R),
        VietCode(Viet.O74, Viet.O73),
        VietCode(Viet.O75, Viet.O73),
        VietCode(Viet.o7, Viet.o73),
        VietCode(Viet.o71, Viet.o73),
        VietCode(Viet.o72, Viet.o73),
        VietCode(Viet.o73, Viet.o7, Viet.R),
        VietCode(Viet.o74, Viet.o73),
        VietCode(Viet.o75, Viet.o73),
        VietCode(Viet.U, Viet.U3),
        VietCode(Viet.U1, Viet.U3),
        VietCode(Viet.U2, Viet.U3),
        VietCode(Viet.U3, Viet.U, Viet.R),
        VietCode(Viet.U4, Viet.U3),
        VietCode(Viet.U5, Viet.U3),
        VietCode(Viet.u, Viet.u3),
        VietCode(Viet.u1, Viet.u3),
        VietCode(Viet.u2, Viet.u3),
        VietCode(Viet.u3, Viet.u, Viet.R),
        VietCode(Viet.u4, Viet.u3),
        VietCode(Viet.u5, Viet.u3),
        VietCode(Viet.U7, Viet.U73),
        VietCode(Viet.U71, Viet.U73),
        VietCode(Viet.U72, Viet.U73),
        VietCode(Viet.U73, Viet.U7, Viet.R),
        VietCode(Viet.U74, Viet.U73),
        VietCode(Viet.U75, Viet.U73),
        VietCode(Viet.u7, Viet.u73),
        VietCode(Viet.u71, Viet.u73),
        VietCode(Viet.u72, Viet.u73),
        VietCode(Viet.u73, Viet.u7, Viet.R),
        VietCode(Viet.u74, Viet.u73),
        VietCode(Viet.u75, Viet.u73),
        VietCode(Viet.I, Viet.I3),
        VietCode(Viet.I1, Viet.I3),
        VietCode(Viet.I2, Viet.I3),
        VietCode(Viet.I3, Viet.I, Viet.R),
        VietCode(Viet.I4, Viet.I3),
        VietCode(Viet.I5, Viet.I3),
        VietCode(Viet.i, Viet.i3),
        VietCode(Viet.i1, Viet.i3),
        VietCode(Viet.i2, Viet.i3),
        VietCode(Viet.i3, Viet.i, Viet.R),
        VietCode(Viet.i4, Viet.i3),
        VietCode(Viet.i5, Viet.i3),
        VietCode(Viet.Y, Viet.Y3),
        VietCode(Viet.Y1, Viet.Y3),
        VietCode(Viet.Y2, Viet.Y3),
        VietCode(Viet.Y3, Viet.Y, Viet.R),
        VietCode(Viet.Y4, Viet.Y3),
        VietCode(Viet.Y5, Viet.Y3),
        VietCode(Viet.y, Viet.y3),
        VietCode(Viet.y1, Viet.y3),
        VietCode(Viet.y2, Viet.y3),
        VietCode(Viet.y3, Viet.y, Viet.R),
        VietCode(Viet.y4, Viet.y3),
        VietCode(Viet.y5, Viet.y3)
    ]

    static let code_r: [VietCode] = [
        VietCode(Viet.A, Viet.A3),
        VietCode(Viet.A1, Viet.A3),
        VietCode(Viet.A2, Viet.A3),
        VietCode(Viet.A3, Viet.A, Viet.r),
        VietCode(Viet.A4, Viet.A3),
        VietCode(Viet.A5, Viet.A3),
        VietCode(Viet.a, Viet.a3),
        VietCode(Viet.a1, Viet.a3),
        VietCode(Viet.a2, Viet.a3),
        VietCode(Viet.a3, Viet.a, Viet.r),
        VietCode(Viet.a4, Viet.a3),
        VietCode(Viet.a5, Viet.a3),
        VietCode(Viet.A6, Viet.A63),
        VietCode(Viet.A61, Viet.A63),
        VietCode(Viet.A62, Viet.A63),
        VietCode(Viet.A63, Viet.A6, Viet.r),
        VietCode(Viet.A64, Viet.A63),
        VietCode(Viet.A65, Viet.A63),
        VietCode(Viet.a6, Viet.a63),
        VietCode(Viet.a61, Viet.a63),
        VietCode(Viet.a62, Viet.a63),
        VietCode(Viet.a63, Viet.a6, Viet.r),
        VietCode(Viet.a64, Viet.a63),
        VietCode(Viet.a65, Viet.a63),
        VietCode(Viet.A8, Viet.A83),
        VietCode(Viet.A81, Viet.A83),
        VietCode(Viet.A82, Viet.A83),
        VietCode(Viet.A83, Viet.A8, Viet.r),
        VietCode(Viet.A84, Viet.A83),
        VietCode(Viet.A85, Viet.A83),
        VietCode(Viet.a8, Viet.a83),
        VietCode(Viet.a81, Viet.a83),
        VietCode(Viet.a82, Viet.a83),
        VietCode(Viet.a83, Viet.a8, Viet.r),
        VietCode(Viet.a84, Viet.a83),
        VietCode(Viet.a85, Viet.a83),
        VietCode(Viet.E, Viet.E3),
        VietCode(Viet.E1, Viet.E3),
        VietCode(Viet.E2, Viet.E3),
        VietCode(Viet.E3, Viet.E, Viet.r),
        VietCode(Viet.E4, Viet.E3),
        VietCode(Viet.E5, Viet.E3),
        VietCode(Viet.e, Viet.e3),
        VietCode(Viet.e1, Viet.e3),
        VietCode(Viet.e2, Viet.e3),
        VietCode(Viet.e3, Viet.e, Viet.r),
        VietCode(Viet.e4, Viet.e3),
        VietCode(Viet.e5, Viet.e3),
        VietCode(Viet.E6, Viet.E63),
        VietCode(Viet.E61, Viet.E63),
        VietCode(Viet.E62, Viet.E63),
        VietCode(Viet.E63, Viet.E6, Viet.r),
        VietCode(Viet.E64, Viet.E63),
        VietCode(Viet.E65, Viet.E63),
        VietCode(Viet.e6, Viet.e63),
        VietCode(Viet.e61, Viet.e63),
        VietCode(Viet.e62, Viet.e63),
        VietCode(Viet.e63, Viet.e6, Viet.r),
        VietCode(Viet.e64, Viet.e63),
        VietCode(Viet.e65, Viet.e63),
        VietCode(Viet.O, Viet.O3),
        VietCode(Viet.O1, Viet.O3),
        VietCode(Viet.O2, Viet.O3),
        VietCode(Viet.O3, Viet.O, Viet.r),
        VietCode(Viet.O4, Viet.O3),
        VietCode(Viet.O5, Viet.O3),
        VietCode(Viet.o, Viet.o3),
        VietCode(Viet.o1, Viet.o3),
        VietCode(Viet.o2, Viet.o3),
        VietCode(Viet.o3, Viet.o, Viet.r),
        VietCode(Viet.o4, Viet.o3),
        VietCode(Viet.o5, Viet.o3),
        VietCode(Viet.O6, Viet.O63),
        VietCode(Viet.O61, Viet.O63),
        VietCode(Viet.O62, Viet.O63),
        VietCode(Viet.O63, Viet.O6, Viet.r),
        VietCode(Viet.O64, Viet.O63),
        VietCode(Viet.O65, Viet.O63),
        VietCode(Viet.o6, Viet.o63),
        VietCode(Viet.o61, Viet.o63),
        VietCode(Viet.o62, Viet.o63),
        VietCode(Viet.o63, Viet.o6, Viet.r),
        VietCode(Viet.o64, Viet.o63),
        VietCode(Viet.o65, Viet.o63),
        VietCode(Viet.O7, Viet.O73),
        VietCode(Viet.O71, Viet.O73),
        VietCode(Viet.O72, Viet.O73),
        VietCode(Viet.O73, Viet.O7, Viet.r),
        VietCode(Viet.O74, Viet.O73),
        VietCode(Viet.O75, Viet.O73),
        VietCode(Viet.o7, Viet.o73),
        VietCode(Viet.o71, Viet.o73),
        VietCode(Viet.o72, Viet.o73),
        VietCode(Viet.o73, Viet.o7, Viet.r),
        VietCode(Viet.o74, Viet.o73),
        VietCode(Viet.o75, Viet.o73),
        VietCode(Viet.U, Viet.U3),
        VietCode(Viet.U1, Viet.U3),
        VietCode(Viet.U2, Viet.U3),
        VietCode(Viet.U3, Viet.U, Viet.r),
        VietCode(Viet.U4, Viet.U3),
        VietCode(Viet.U5, Viet.U3),
        VietCode(Viet.u, Viet.u3),
        VietCode(Viet.u1, Viet.u3),
        VietCode(Viet.u2, Viet.u3),
        VietCode(Viet.u3, Viet.u, Viet.r),
        VietCode(Viet.u4, Viet.u3),
        VietCode(Viet.u5, Viet.u3),
        VietCode(Viet.U7, Viet.U73),
        VietCode(Viet.U71, Viet.U73),
        VietCode(Viet.U72, Viet.U73),
        VietCode(Viet.U73, Viet.U7, Viet.r),
        VietCode(Viet.U74, Viet.U73),
        VietCode(Viet.U75, Viet.U73),
        VietCode(Viet.u7, Viet.u73),
        VietCode(Viet.u71, Viet.u73),
        VietCode(Viet.u72, Viet.u73),
        VietCode(Viet.u73, Viet.u7, Viet.r),
        VietCode(Viet.u74, Viet.u73),
        VietCode(Viet.u75, Viet.u73),
        VietCode(Viet.I, Viet.I3),
        VietCode(Viet.I1, Viet.I3),
        VietCode(Viet.I2, Viet.I3),
        VietCode(Viet.I3, Viet.I, Viet.r),
        VietCode(Viet.I4, Viet.I3),
        VietCode(Viet.I5, Viet.I3),
        VietCode(Viet.i, Viet.i3),
        VietCode(Viet.i1, Viet.i3),
        VietCode(Viet.i2, Viet.i3),
        VietCode(Viet.i3, Viet.i, Viet.r),
        VietCode(Viet.i4, Viet.i3),
        VietCode(Viet.i5, Viet.i3),
        VietCode(Viet.Y, Viet.Y3),
        VietCode(Viet.Y1, Viet.Y3),
        VietCode(Viet.Y2, Viet.Y3),
        VietCode(Viet.Y3, Viet.Y, Viet.r),
        VietCode(Viet.Y4, Viet.Y3),
        VietCode(Viet.Y5, Viet.Y3),
        VietCode(Viet.y, Viet.y3),
        VietCode(Viet.y1, Viet.y3),
        VietCode(Viet.y2, Viet.y3),
        VietCode(Viet.y3, Viet.y, Viet.r),
        VietCode(Viet.y4, Viet.y3),
        VietCode(Viet.y5, Viet.y3)
    ]

    static let code_X: [VietCode] = [
        VietCode(Viet.A, Viet.A4),
        VietCode(Viet.A1, Viet.A4),
        VietCode(Viet.A2, Viet.A4),
        VietCode(Viet.A3, Viet.A4),
        VietCode(Viet.A4, Viet.A, Viet.X),
        VietCode(Viet.A5, Viet.A4),
        VietCode(Viet.a, Viet.a4),
        VietCode(Viet.a1, Viet.a4),
        VietCode(Viet.a2, Viet.a4),
        VietCode(Viet.a3, Viet.a4),
        VietCode(Viet.a4, Viet.a, Viet.X),
        VietCode(Viet.a5, Viet.a4),
        VietCode(Viet.A6, Viet.A64),
        VietCode(Viet.A61, Viet.A64),
        VietCode(Viet.A62, Viet.A64),
        VietCode(Viet.A63, Viet.A64),
        VietCode(Viet.A64, Viet.A6, Viet.X),
        VietCode(Viet.A65, Viet.A64),
        VietCode(Viet.a6, Viet.a64),
        VietCode(Viet.a61, Viet.a64),
        VietCode(Viet.a62, Viet.a64),
        VietCode(Viet.a63, Viet.a64),
        VietCode(Viet.a64, Viet.a6, Viet.X),
        VietCode(Viet.a65, Viet.a64),
        VietCode(Viet.A8, Viet.A84),
        VietCode(Viet.A81, Viet.A84),
        VietCode(Viet.A82, Viet.A84),
        VietCode(Viet.A83, Viet.A84),
        VietCode(Viet.A84, Viet.A8, Viet.X),
        VietCode(Viet.A85, Viet.A84),
        VietCode(Viet.a8, Viet.a84),
        VietCode(Viet.a81, Viet.a84),
        VietCode(Viet.a82, Viet.a84),
        VietCode(Viet.a83, Viet.a84),
        VietCode(Viet.a84, Viet.a8, Viet.X),
        VietCode(Viet.a85, Viet.a84),
        VietCode(Viet.E, Viet.E4),
        VietCode(Viet.E1, Viet.E4),
        VietCode(Viet.E2, Viet.E4),
        VietCode(Viet.E3, Viet.E4),
        VietCode(Viet.E4, Viet.E, Viet.X),
        VietCode(Viet.E5, Viet.E4),
        VietCode(Viet.e, Viet.e4),
        VietCode(Viet.e1, Viet.e4),
        VietCode(Viet.e2, Viet.e4),
        VietCode(Viet.e3, Viet.e4),
        VietCode(Viet.e4, Viet.e, Viet.X),
        VietCode(Viet.e5, Viet.e4),
        VietCode(Viet.E6, Viet.E64),
        VietCode(Viet.E61, Viet.E64),
        VietCode(Viet.E62, Viet.E64),
        VietCode(Viet.E63, Viet.E64),
        VietCode(Viet.E64, Viet.E6, Viet.X),
        VietCode(Viet.E65, Viet.E64),
        VietCode(Viet.e6, Viet.e64),
        VietCode(Viet.e61, Viet.e64),
        VietCode(Viet.e62, Viet.e64),
        VietCode(Viet.e63, Viet.e64),
        VietCode(Viet.e64, Viet.e6, Viet.X),
        VietCode(Viet.e65, Viet.e64),
        VietCode(Viet.O, Viet.O4),
        VietCode(Viet.O1, Viet.O4),
        VietCode(Viet.O2, Viet.O4),
        VietCode(Viet.O3, Viet.O4),
        VietCode(Viet.O4, Viet.O, Viet.X),
        VietCode(Viet.O5, Viet.O4),
        VietCode(Viet.o, Viet.o4),
        VietCode(Viet.o1, Viet.o4),
        VietCode(Viet.o2, Viet.o4),
        VietCode(Viet.o3, Viet.o4),
        VietCode(Viet.o4, Viet.o, Viet.X),
        VietCode(Viet.o5, Viet.o4),
        VietCode(Viet.O6, Viet.O64),
        VietCode(Viet.O61, Viet.O64),
        VietCode(Viet.O62, Viet.O64),
        VietCode(Viet.O63, Viet.O64),
        VietCode(Viet.O64, Viet.O6, Viet.X),
        VietCode(Viet.O65, Viet.O64),
        VietCode(Viet.o6, Viet.o64),
        VietCode(Viet.o61, Viet.o64),
        VietCode(Viet.o62, Viet.o64),
        VietCode(Viet.o63, Viet.o64),
        VietCode(Viet.o64, Viet.o6, Viet.X),
        VietCode(Viet.o65, Viet.o64),
        VietCode(Viet.O7, Viet.O74),
        VietCode(Viet.O71, Viet.O74),
        VietCode(Viet.O72, Viet.O74),
        VietCode(Viet.O73, Viet.O74),
        VietCode(Viet.O74, Viet.O7, Viet.X),
        VietCode(Viet.O75, Viet.O74),
        VietCode(Viet.o7, Viet.o74),
        VietCode(Viet.o71, Viet.o74),
        VietCode(Viet.o72, Viet.o74),
        VietCode(Viet.o73, Viet.o74),
        VietCode(Viet.o74, Viet.o7, Viet.X),
        VietCode(Viet.o75, Viet.o74),
        VietCode(Viet.U, Viet.U4),
        VietCode(Viet.U1, Viet.U4),
        VietCode(Viet.U2, Viet.U4),
        VietCode(Viet.U3, Viet.U4),
        VietCode(Viet.U4, Viet.U, Viet.X),
        VietCode(Viet.U5, Viet.U4),
        VietCode(Viet.u, Viet.u4),
        VietCode(Viet.u1, Viet.u4),
        VietCode(Viet.u2, Viet.u4),
        VietCode(Viet.u3, Viet.u4),
        VietCode(Viet.u4, Viet.u, Viet.X),
        VietCode(Viet.u5, Viet.u4),
        VietCode(Viet.U7, Viet.U74),
        VietCode(Viet.U71, Viet.U74),
        VietCode(Viet.U72, Viet.U74),
        VietCode(Viet.U73, Viet.U74),
        VietCode(Viet.U74, Viet.U7, Viet.X),
        VietCode(Viet.U75, Viet.U74),
        VietCode(Viet.u7, Viet.u74),
        VietCode(Viet.u71, Viet.u74),
        VietCode(Viet.u72, Viet.u74),
        VietCode(Viet.u73, Viet.u74),
        VietCode(Viet.u74, Viet.u7, Viet.X),
        VietCode(Viet.u75, Viet.U74),
        VietCode(Viet.I, Viet.I4),
        VietCode(Viet.I1, Viet.I4),
        VietCode(Viet.I2, Viet.I4),
        VietCode(Viet.I3, Viet.I4),
        VietCode(Viet.I4, Viet.I, Viet.X),
        VietCode(Viet.I5, Viet.I4),
        VietCode(Viet.i, Viet.i4),
        VietCode(Viet.i1, Viet.i4),
        VietCode(Viet.i2, Viet.i4),
        VietCode(Viet.i3, Viet.i4),
        VietCode(Viet.i4, Viet.i, Viet.X),
        VietCode(Viet.i5, Viet.i4),
        VietCode(Viet.Y, Viet.Y4),
        VietCode(Viet.Y1, Viet.Y4),
        VietCode(Viet.Y2, Viet.Y4),
        VietCode(Viet.Y3, Viet.Y4),
        VietCode(Viet.Y4, Viet.Y, Viet.X),
        VietCode(Viet.Y5, Viet.Y4),
        VietCode(Viet.y, Viet.y4),
        VietCode(Viet.y1, Viet.y4),
        VietCode(Viet.y2, Viet.y4),
        VietCode(Viet.y3, Viet.y4),
        VietCode(Viet.y4, Viet.y, Viet.X),
        VietCode(Viet.y5, Viet.y4)
    ]

    static let code_x: [VietCode] = [
        VietCode(Viet.A, Viet.A4),
        VietCode(Viet.A1, Viet.A4),
        VietCode(Viet.A2, Viet.A4),
        VietCode(Viet.A3, Viet.A4),
        VietCode(Viet.A4, Viet.A, Viet.x),
        VietCode(Viet.A5, Viet.A4),
        VietCode(Viet.a, Viet.a4),
        VietCode(Viet.a1, Viet.a4),
        VietCode(Viet.a2, Viet.a4),
        VietCode(Viet.a3, Viet.a4),
        VietCode(Viet.a4, Viet.a, Viet.x),
        VietCode(Viet.a5, Viet.a4),
        VietCode(Viet.A6, Viet.A64),
        VietCode(Viet.A61, Viet.A64),
        VietCode(Viet.A62, Viet.A64),
        VietCode(Viet.A63, Viet.A64),
        VietCode(Viet.A64, Viet.A6, Viet.x),
        VietCode(Viet.A65, Viet.A64),
        VietCode(Viet.a6, Viet.a64),
        VietCode(Viet.a61, Viet.a64),
        VietCode(Viet.a62, Viet.a64),
        VietCode(Viet.a63, Viet.a64),
        VietCode(Viet.a64, Viet.a6, Viet.x),
        VietCode(Viet.a65, Viet.a64),
        VietCode(Viet.A8, Viet.A84),
        VietCode(Viet.A81, Viet.A84),
        VietCode(Viet.A82, Viet.A84),
        VietCode(Viet.A83, Viet.A84),
        VietCode(Viet.A84, Viet.A8, Viet.x),
        VietCode(Viet.A85, Viet.A84),
        VietCode(Viet.a8, Viet.a84),
        VietCode(Viet.a81, Viet.a84),
        VietCode(Viet.a82, Viet.a84),
        VietCode(Viet.a83, Viet.a84),
        VietCode(Viet.a84, Viet.a8, Viet.x),
        VietCode(Viet.a85, Viet.a84),
        VietCode(Viet.E, Viet.E4),
        VietCode(Viet.E1, Viet.E4),
        VietCode(Viet.E2, Viet.E4),
        VietCode(Viet.E3, Viet.E4),
        VietCode(Viet.E4, Viet.E, Viet.x),
        VietCode(Viet.E5, Viet.E4),
        VietCode(Viet.e, Viet.e4),
        VietCode(Viet.e1, Viet.e4),
        VietCode(Viet.e2, Viet.e4),
        VietCode(Viet.e3, Viet.e4),
        VietCode(Viet.e4, Viet.e, Viet.x),
        VietCode(Viet.e5, Viet.e4),
        VietCode(Viet.E6, Viet.E64),
        VietCode(Viet.E61, Viet.E64),
        VietCode(Viet.E62, Viet.E64),
        VietCode(Viet.E63, Viet.E64),
        VietCode(Viet.E64, Viet.E6, Viet.x),
        VietCode(Viet.E65, Viet.E64),
        VietCode(Viet.e6, Viet.e64),
        VietCode(Viet.e61, Viet.e64),
        VietCode(Viet.e62, Viet.e64),
        VietCode(Viet.e63, Viet.e64),
        VietCode(Viet.e64, Viet.e6, Viet.x),
        VietCode(Viet.e65, Viet.e64),
        VietCode(Viet.O, Viet.O4),
        VietCode(Viet.O1, Viet.O4),
        VietCode(Viet.O2, Viet.O4),
        VietCode(Viet.O3, Viet.O4),
        VietCode(Viet.O4, Viet.O, Viet.x),
        VietCode(Viet.O5, Viet.O4),
        VietCode(Viet.o, Viet.o4),
        VietCode(Viet.o1, Viet.o4),
        VietCode(Viet.o2, Viet.o4),
        VietCode(Viet.o3, Viet.o4),
        VietCode(Viet.o4, Viet.o, Viet.x),
        VietCode(Viet.o5, Viet.o4),
        VietCode(Viet.O6, Viet.O64),
        VietCode(Viet.O61, Viet.O64),
        VietCode(Viet.O62, Viet.O64),
        VietCode(Viet.O63, Viet.O64),
        VietCode(Viet.O64, Viet.O6, Viet.x),
        VietCode(Viet.O65, Viet.O64),
        VietCode(Viet.o6, Viet.o64),
        VietCode(Viet.o61, Viet.o64),
        VietCode(Viet.o62, Viet.o64),
        VietCode(Viet.o63, Viet.o64),
        VietCode(Viet.o64, Viet.o6, Viet.x),
        VietCode(Viet.o65, Viet.o64),
        VietCode(Viet.O7, Viet.O74),
        VietCode(Viet.O71, Viet.O74),
        VietCode(Viet.O72, Viet.O74),
        VietCode(Viet.O73, Viet.O74),
        VietCode(Viet.O74, Viet.O7, Viet.x),
        VietCode(Viet.O75, Viet.O74),
        VietCode(Viet.o7, Viet.o74),
        VietCode(Viet.o71, Viet.o74),
        VietCode(Viet.o72, Viet.o74),
        VietCode(Viet.o73, Viet.o74),
        VietCode(Viet.o74, Viet.o7, Viet.x),
        VietCode(Viet.o75, Viet.o74),
        VietCode(Viet.U, Viet.U4),
        VietCode(Viet.U1, Viet.U4),
        VietCode(Viet.U2, Viet.U4),
        VietCode(Viet.U3, Viet.U4),
        VietCode(Viet.U4, Viet.U, Viet.x),
        VietCode(Viet.U5, Viet.U4),
        VietCode(Viet.u, Viet.u4),
        VietCode(Viet.u1, Viet.u4),
        VietCode(Viet.u2, Viet.u4),
        VietCode(Viet.u3, Viet.u4),
        VietCode(Viet.u4, Viet.u, Viet.x),
        VietCode(Viet.u5, Viet.u4),
        VietCode(Viet.U7, Viet.U74),
        VietCode(Viet.U71, Viet.U74),
        VietCode(Viet.U72, Viet.U74),
        VietCode(Viet.U73, Viet.U74),
        VietCode(Viet.U74, Viet.U7, Viet.x),
        VietCode(Viet.U75, Viet.U74),
        VietCode(Viet.u7, Viet.u74),
        VietCode(Viet.u71, Viet.u74),
        VietCode(Viet.u72, Viet.u74),
        VietCode(Viet.u73, Viet.u74),
        VietCode(Viet.u74, Viet.u7, Viet.x),
        VietCode(Viet.u75, Viet.u74),
        VietCode(Viet.I, Viet.I4),
        VietCode(Viet.I1, Viet.I4),
        VietCode(Viet.I2, Viet.I4),
        VietCode(Viet.I3, Viet.I4),
        VietCode(Viet.I4, Viet.I, Viet.x),
        VietCode(Viet.I5, Viet.I4),
        VietCode(Viet.i, Viet.i4),
        VietCode(Viet.i1, Viet.i4),
        VietCode(Viet.i2, Viet.i4),
        VietCode(Viet.i3, Viet.i4),
        VietCode(Viet.i4, Viet.i, Viet.x),
        VietCode(Viet.i5, Viet.i4),
        VietCode(Viet.Y, Viet.Y4),
        VietCode(Viet.Y1, Viet.Y4),
        VietCode(Viet.Y2, Viet.Y4),
        VietCode(Viet.Y3, Viet.Y4),
        VietCode(Viet.Y4, Viet.Y, Viet.x),
        VietCode(Viet.Y5, Viet.Y4),
        VietCode(Viet.y, Viet.y4),
        VietCode(Viet.y1, Viet.y4),
        VietCode(Viet.y2, Viet.y4),
        VietCode(Viet.y3, Viet.y4),
        VietCode(Viet.y4, Viet.y, Viet.x),
        VietCode(Viet.y5, Viet.y4)
    ]

    static let code_J: [VietCode] = [
        VietCode(Viet.A, Viet.A5),
        VietCode(Viet.A1, Viet.A5),
        VietCode(Viet.A2, Viet.A5),
        VietCode(Viet.A3, Viet.A5),
        VietCode(Viet.A4, Viet.A5),
        VietCode(Viet.A5, Viet.A, Viet.J),
        VietCode(Viet.a, Viet.a5),
        VietCode(Viet.a1, Viet.a5),
        VietCode(Viet.a2, Viet.a5),
        VietCode(Viet.a3, Viet.a5),
        VietCode(Viet.a4, Viet.a5),
        VietCode(Viet.a5, Viet.a, Viet.J),
        VietCode(Viet.A6, Viet.A65),
        VietCode(Viet.A61, Viet.A65),
        VietCode(Viet.A62, Viet.A65),
        VietCode(Viet.A63, Viet.A65),
        VietCode(Viet.A64, Viet.A65),
        VietCode(Viet.A65, Viet.A6, Viet.J),
        VietCode(Viet.a6, Viet.a65),
        VietCode(Viet.a61, Viet.a65),
        VietCode(Viet.a62, Viet.a65),
        VietCode(Viet.a63, Viet.a65),
        VietCode(Viet.a64, Viet.a65),
        VietCode(Viet.a65, Viet.a6, Viet.J),
        VietCode(Viet.A8, Viet.A85),
        VietCode(Viet.A81, Viet.A85),
        VietCode(Viet.A82, Viet.A85),
        VietCode(Viet.A83, Viet.A85),
        VietCode(Viet.A84, Viet.A85),
        VietCode(Viet.A85, Viet.A8, Viet.J),
        VietCode(Viet.a8, Viet.a85),
        VietCode(Viet.a81, Viet.a85),
        VietCode(Viet.a82, Viet.a85),
        VietCode(Viet.a83, Viet.a85),
        VietCode(Viet.a84, Viet.a85),
        VietCode(Viet.a85, Viet.a8, Viet.J),
        VietCode(Viet.E, Viet.E5),
        VietCode(Viet.E1, Viet.E5),
        VietCode(Viet.E2, Viet.E5),
        VietCode(Viet.E3, Viet.E5),
        VietCode(Viet.E4, Viet.E5),
        VietCode(Viet.E5, Viet.E, Viet.J),
        VietCode(Viet.e, Viet.e5),
        VietCode(Viet.e1, Viet.e5),
        VietCode(Viet.e2, Viet.e5),
        VietCode(Viet.e3, Viet.e5),
        VietCode(Viet.e4, Viet.e5),
        VietCode(Viet.e5, Viet.e, Viet.J),
        VietCode(Viet.E6, Viet.E65),
        VietCode(Viet.E61, Viet.E65),
        VietCode(Viet.E62, Viet.E65),
        VietCode(Viet.E63, Viet.E65),
        VietCode(Viet.E64, Viet.E65),
        VietCode(Viet.E65, Viet.E6, Viet.J),
        VietCode(Viet.e6, Viet.e65),
        VietCode(Viet.e61, Viet.e65),
        VietCode(Viet.e62, Viet.e65),
        VietCode(Viet.e63, Viet.e65),
        VietCode(Viet.e64, Viet.e65),
        VietCode(Viet.e65, Viet.e6, Viet.J),
        VietCode(Viet.O, Viet.O5),
        VietCode(Viet.O1, Viet.O5),
        VietCode(Viet.O2, Viet.O5),
        VietCode(Viet.O3, Viet.O5),
        VietCode(Viet.O4, Viet.O5),
        VietCode(Viet.O5, Viet.O, Viet.J),
        VietCode(Viet.o, Viet.o5),
        VietCode(Viet.o1, Viet.o5),
        VietCode(Viet.o2, Viet.o5),
        VietCode(Viet.o3, Viet.o5),
        VietCode(Viet.o4, Viet.o5),
        VietCode(Viet.o5, Viet.o, Viet.J),
        VietCode(Viet.O6, Viet.O65),
        VietCode(Viet.O61, Viet.O65),
        VietCode(Viet.O62, Viet.O65),
        VietCode(Viet.O63, Viet.O65),
        VietCode(Viet.O64, Viet.O65),
        VietCode(Viet.O65, Viet.O6, Viet.J),
        VietCode(Viet.o6, Viet.o65),
        VietCode(Viet.o61, Viet.o65),
        VietCode(Viet.o62, Viet.o65),
        VietCode(Viet.o63, Viet.o65),
        VietCode(Viet.o64, Viet.o65),
        VietCode(Viet.o65, Viet.o6, Viet.J),
        VietCode(Viet.O7, Viet.O75),
        VietCode(Viet.O71, Viet.O75),
        VietCode(Viet.O72, Viet.O75),
        VietCode(Viet.O73, Viet.O75),
        VietCode(Viet.O74, Viet.O75),
        VietCode(Viet.O75, Viet.O7, Viet.J),
        VietCode(Viet.o7, Viet.o75),
        VietCode(Viet.o71, Viet.o75),
        VietCode(Viet.o72, Viet.o75),
        VietCode(Viet.o73, Viet.o75),
        VietCode(Viet.o74, Viet.o75),
        VietCode(Viet.o75, Viet.o7, Viet.J),
        VietCode(Viet.U, Viet.U5),
        VietCode(Viet.U1, Viet.U5),
        VietCode(Viet.U2, Viet.U5),
        VietCode(Viet.U3, Viet.U5),
        VietCode(Viet.U4, Viet.U5),
        VietCode(Viet.U5, Viet.U, Viet.J),
        VietCode(Viet.u, Viet.u5),
        VietCode(Viet.u1, Viet.u5),
        VietCode(Viet.u2, Viet.u5),
        VietCode(Viet.u3, Viet.u5),
        VietCode(Viet.u4, Viet.u5),
        VietCode(Viet.u5, Viet.u, Viet.J),
        VietCode(Viet.U7, Viet.U75),
        VietCode(Viet.U71, Viet.U75),
        VietCode(Viet.U72, Viet.U75),
        VietCode(Viet.U73, Viet.U75),
        VietCode(Viet.U74, Viet.U75),
        VietCode(Viet.U75, Viet.U7, Viet.J),
        VietCode(Viet.u7, Viet.u75),
        VietCode(Viet.u71, Viet.u75),
        VietCode(Viet.u72, Viet.u75),
        VietCode(Viet.u73, Viet.u75),
        VietCode(Viet.u74, Viet.u75),
        VietCode(Viet.u75, Viet.u7, Viet.J),
        VietCode(Viet.I, Viet.I5),
        VietCode(Viet.I1, Viet.I5),
        VietCode(Viet.I2, Viet.I5),
        VietCode(Viet.I3, Viet.I5),
        VietCode(Viet.I4, Viet.I5),
        VietCode(Viet.I5, Viet.I, Viet.J),
        VietCode(Viet.i, Viet.i5),
        VietCode(Viet.i1, Viet.i5),
        VietCode(Viet.i2, Viet.i5),
        VietCode(Viet.i3, Viet.i5),
        VietCode(Viet.i4, Viet.i5),
        VietCode(Viet.i5, Viet.i, Viet.J),
        VietCode(Viet.Y, Viet.Y5),
        VietCode(Viet.Y1, Viet.Y5),
        VietCode(Viet.Y2, Viet.Y5),
        VietCode(Viet.Y3, Viet.Y5),
        VietCode(Viet.Y4, Viet.Y5),
        VietCode(Viet.Y5, Viet.Y, Viet.J),
        VietCode(Viet.y, Viet.y5),
        VietCode(Viet.y1, Viet.y5),
        VietCode(Viet.y2, Viet.y5),
        VietCode(Viet.y3, Viet.y5),
        VietCode(Viet.y4, Viet.y5),
        VietCode(Viet.y5, Viet.y, Viet.J)
    ]

    static let code_j: [VietCode] = [
        VietCode(Viet.A, Viet.A5),
        VietCode(Viet.A1, Viet.A5),
        VietCode(Viet.A2, Viet.A5),
        VietCode(Viet.A3, Viet.A5),
        VietCode(Viet.A4, Viet.A5),
        VietCode(Viet.A5, Viet.A, Viet.j),
        VietCode(Viet.a, Viet.a5),
        VietCode(Viet.a1, Viet.a5),
        VietCode(Viet.a2, Viet.a5),
        VietCode(Viet.a3, Viet.a5),
        VietCode(Viet.a4, Viet.a5),
        VietCode(Viet.a5, Viet.a, Viet.j),
        VietCode(Viet.A6, Viet.A65),
        VietCode(Viet.A61, Viet.A65),
        VietCode(Viet.A62, Viet.A65),
        VietCode(Viet.A63, Viet.A65),
        VietCode(Viet.A64, Viet.A65),
        VietCode(Viet.A65, Viet.A6, Viet.j),
        VietCode(Viet.a6, Viet.a65),
        VietCode(Viet.a61, Viet.a65),
        VietCode(Viet.a62, Viet.a65),
        VietCode(Viet.a63, Viet.a65),
        VietCode(Viet.a64, Viet.a65),
        VietCode(Viet.a65, Viet.a6, Viet.j),
        VietCode(Viet.A8, Viet.A85),
        VietCode(Viet.A81, Viet.A85),
        VietCode(Viet.A82, Viet.A85),
        VietCode(Viet.A83, Viet.A85),
        VietCode(Viet.A84, Viet.A85),
        VietCode(Viet.A85, Viet.A8, Viet.j),
        VietCode(Viet.a8, Viet.a85),
        VietCode(Viet.a81, Viet.a85),
        VietCode(Viet.a82, Viet.a85),
        VietCode(Viet.a83, Viet.a85),
        VietCode(Viet.a84, Viet.a85),
        VietCode(Viet.a85, Viet.a8, Viet.j),
        VietCode(Viet.E, Viet.E5),
        VietCode(Viet.E1, Viet.E5),
        VietCode(Viet.E2, Viet.E5),
        VietCode(Viet.E3, Viet.E5),
        VietCode(Viet.E4, Viet.E5),
        VietCode(Viet.E5, Viet.E, Viet.j),
        VietCode(Viet.e, Viet.e5),
        VietCode(Viet.e1, Viet.e5),
        VietCode(Viet.e2, Viet.e5),
        VietCode(Viet.e3, Viet.e5),
        VietCode(Viet.e4, Viet.e5),
        VietCode(Viet.e5, Viet.e, Viet.j),
        VietCode(Viet.E6, Viet.E65),
        VietCode(Viet.E61, Viet.E65),
        VietCode(Viet.E62, Viet.E65),
        VietCode(Viet.E63, Viet.E65),
        VietCode(Viet.E64, Viet.E65),
        VietCode(Viet.E65, Viet.E6, Viet.j),
        VietCode(Viet.e6, Viet.e65),
        VietCode(Viet.e61, Viet.e65),
        VietCode(Viet.e62, Viet.e65),
        VietCode(Viet.e63, Viet.e65),
        VietCode(Viet.e64, Viet.e65),
        VietCode(Viet.e65, Viet.e6, Viet.j),
        VietCode(Viet.O, Viet.O5),
        VietCode(Viet.O1, Viet.O5),
        VietCode(Viet.O2, Viet.O5),
        VietCode(Viet.O3, Viet.O5),
        VietCode(Viet.O4, Viet.O5),
        VietCode(Viet.O5, Viet.O, Viet.j),
        VietCode(Viet.o, Viet.o5),
        VietCode(Viet.o1, Viet.o5),
        VietCode(Viet.o2, Viet.o5),
        VietCode(Viet.o3, Viet.o5),
        VietCode(Viet.o4, Viet.o5),
        VietCode(Viet.o5, Viet.o, Viet.j),
        VietCode(Viet.O6, Viet.O65),
        VietCode(Viet.O61, Viet.O65),
        VietCode(Viet.O62, Viet.O65),
        VietCode(Viet.O63, Viet.O65),
        VietCode(Viet.O64, Viet.O65),
        VietCode(Viet.O65, Viet.O6, Viet.j),
        VietCode(Viet.o6, Viet.o65),
        VietCode(Viet.o61, Viet.o65),
        VietCode(Viet.o62, Viet.o65),
        VietCode(Viet.o63, Viet.o65),
        VietCode(Viet.o64, Viet.o65),
        VietCode(Viet.o65, Viet.o6, Viet.j),
        VietCode(Viet.O7, Viet.O75),
        VietCode(Viet.O71, Viet.O75),
        VietCode(Viet.O72, Viet.O75),
        VietCode(Viet.O73, Viet.O75),
        VietCode(Viet.O74, Viet.O75),
        VietCode(Viet.O75, Viet.O7, Viet.j),
        VietCode(Viet.o7, Viet.o75),
        VietCode(Viet.o71, Viet.o75),
        VietCode(Viet.o72, Viet.o75),
        VietCode(Viet.o73, Viet.o75),
        VietCode(Viet.o74, Viet.o75),
        VietCode(Viet.o75, Viet.o7, Viet.j),
        VietCode(Viet.U, Viet.U5),
        VietCode(Viet.U1, Viet.U5),
        VietCode(Viet.U2, Viet.U5),
        VietCode(Viet.U3, Viet.U5),
        VietCode(Viet.U4, Viet.U5),
        VietCode(Viet.U5, Viet.U, Viet.j),
        VietCode(Viet.u, Viet.u5),
        VietCode(Viet.u1, Viet.u5),
        VietCode(Viet.u2, Viet.u5),
        VietCode(Viet.u3, Viet.u5),
        VietCode(Viet.u4, Viet.u5),
        VietCode(Viet.u5, Viet.u, Viet.j),
        VietCode(Viet.U7, Viet.U75),
        VietCode(Viet.U71, Viet.U75),
        VietCode(Viet.U72, Viet.U75),
        VietCode(Viet.U73, Viet.U75),
        VietCode(Viet.U74, Viet.U75),
        VietCode(Viet.U75, Viet.U7, Viet.j),
        VietCode(Viet.u7, Viet.u75),
        VietCode(Viet.u71, Viet.u75),
        VietCode(Viet.u72, Viet.u75),
        VietCode(Viet.u73, Viet.u75),
        VietCode(Viet.u74, Viet.u75),
        VietCode(Viet.u75, Viet.u7, Viet.j),
        VietCode(Viet.I, Viet.I5),
        VietCode(Viet.I1, Viet.I5),
        VietCode(Viet.I2, Viet.I5),
        VietCode(Viet.I3, Viet.I5),
        VietCode(Viet.I4, Viet.I5),
        VietCode(Viet.I5, Viet.I, Viet.j),
        VietCode(Viet.i, Viet.i5),
        VietCode(Viet.i1, Viet.i5),
        VietCode(Viet.i2, Viet.i5),
        VietCode(Viet.i3, Viet.i5),
        VietCode(Viet.i4, Viet.i5),
        VietCode(Viet.i5, Viet.i, Viet.j),
        VietCode(Viet.Y, Viet.Y5),
        VietCode(Viet.Y1, Viet.Y5),
        VietCode(Viet.Y2, Viet.Y5),
        VietCode(Viet.Y3, Viet.Y5),
        VietCode(Viet.Y4, Viet.Y5),
        VietCode(Viet.Y5, Viet.Y, Viet.j),
        VietCode(Viet.y, Viet.y5),
        VietCode(Viet.y1, Viet.y5),
        VietCode(Viet.y2, Viet.y5),
        VietCode(Viet.y3, Viet.y5),
        VietCode(Viet.y4, Viet.y5),
        VietCode(Viet.y5, Viet.y, Viet.j)
    ]
}
